### ISSUE TITLE
String in English when exporting grid

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-samples-src#29]
Go here
https://igniteui.github.io/help-samples/16.2/JA/grid/export-client-events/index.html

Click export
Exporting is in English. It is localized in the other exporting sample (loading indicator)
https://www.screencast.com/t/oUzNd9lHyG6

**Comment by damyanpetev** [comment]
@hanastasov There's a "Exporting..." string in the sample that just needs to be ${Exporting} instead
