### ISSUE TITLE
Button text wrapping in uploader sample

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-samples-src#30]
Go here
https://igniteui.github.io/help-samples/16.2/JA/file-upload/api-events/index.html
Select a file to upload
The upload button wraps on two lines

![image](https://cloud.githubusercontent.com/assets/9548226/24042109/44dce492-0b19-11e7-9d68-5aee178f9443.png)

**Comment by damyanpetev** [comment]
@EmilTanev That button (and its width style) is part of the Upload control and you can see the same text wrap on http://jp.igniteui.com/file-upload/multiple-upload, so this should probably be moved to https://github.com/IgniteUI/ignite-ui
P.S. The button is set to fixed 100px via the `.ui-igupload-summary-button` class so this could be resolved on application level as well.

**Comment by EmilTanev** [comment]
Okay, can this be resolved in the sample application?

**Comment by damyanpetev** [comment]
Moved to https://github.com/IgniteUI/ignite-ui/issues/931
