### ISSUE TITLE
Angular Dialog's sample is looking for a script at the wrong place

### ISSUE THREAD

**Issue by dafo** [IgniteUI/help-samples-src#65]
1. Open help-samples-src\dist\17.2\EN\dialog-window\angular\index.html

**Actual result**: 
Failed to load resource: the server responded with a status of 404 (Not Found) igniteui-angular.js 

**Expected result:**
The sample is loaded

Note: The sample is looking for <script src="http://localhost/ig_ui17.2/js/extensions/igniteui-angular.js"></script>
This script is removed from the installer and needs to be used as a npm package.

**Comment by damyanpetev** [comment]
Will do after https://github.com/IgniteUI/igniteui-angularjs/issues/120 package rename
