### ISSUE TITLE
Data source is not updated with the new UTC date format

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/help-samples-src#81]
Steps to reproduce:

1. Open the following link:
https://igniteui.github.io/help-samples/data-files/northwind.js

2. Observe the date format of all date columns.

**Actual Result**: Dates are in the previously supported format:  "BirthDate": "\/Date(-664761600000)\/"
**Expected Result:** They should be in the new format:  2017-10-23T17:31Z

**Comment by damyanpetev** [comment]
Alrighty, this has been forgotten a bit, but I don't think there's an issue since `new Date(-664761600000)` is `Wed Dec 08 1948 ..` which seems to correspond to what's in the grid on https://www.igniteui.com/help/iggrid-overview
Closing.
